### ISSUE TITLE
no models folder

### ISSUE THREAD

**Issue by nhatanhphung** [ydup/Anomaly-Detection-in-Time-Series-with-Triadic-Motif-Fields#1]
Hello, i recent to try out the network for myself, however when i ran the classifier there was no model. Would it be possible for you to provide the model or do i need to train the model myself? 

Thank you very much!

**Comment by ydup** [comment]
If you are trying to use classifier/, you need to extract the features firstly, then you can train the classifier by yourself.

If you are trying to use the app for interpretation and visualization, we will upload the model weights in paper later, or you can use the models trained by yourself.

**Comment by ydup** [comment]
@nhatanhphung The model weight has been uploaded
